name: Deploy to Azure App Service - Multi Environment

on:
  push:
    branches:
      - dev
      - test
      - uat
jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: 
      name: ${{ github.ref_name }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    env:
      AZURE_WEBAPP_PACKAGE_PATH: '.'
      DOTNET_VERSION: '4.0.x'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish
        run: dotnet publish -c Release -o publish_output

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ fromJSON('{"dev":"your-webapp-dev","test":"your-webapp-dev","uat":"demo-web28"}')[github.ref_name] }}
          publish-profile: ${{ secrets[format('AZURE_WEBAPP_PUBLISH_PROFILE_{0}', upper(github.ref_name))] }}
          package: publish_output
