on:
push:
branches:
- uat

jobs:
build-and-deploy:
runs-on: windows-latest

steps:
- name: Checkout Code
  uses: actions/checkout@v4
- name: Upload to Azure Web App
uses: azure/webapps-deploy@v2
with:
app-name: demo-web28
publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
package: .